### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by matczar** [thanks-to-it/wp-dich#2]
I would like to use your class in a WordPress plugin because it solves a difficult problem. Could you please provide information on the license under which you share your code?

**Comment by pablo-sg-pacheco** [comment]
Hi @matczar ,

I've never thought about it. You can use it as you like :)
Now I'm curious, how did you find this class and could you share what problem does it help to solve?

**Comment by matczar** [comment]
Thanks! Nevertheless, a clear indication of the license would be appreciated as it will be a commercial plugin.

I was just intensively looking for a solution on Google for lazy class loading when using WordPress hooks and dependency injection. I finally ended up here.

I am creating a plugin in which we use Symfony DI and just wanted class instances to be instantiated by DI only when needed, ie when the associated hook is fired.

**Comment by pablo-sg-pacheco** [comment]
Ok, you're right. I just added it.

Thanks for letting me know. In that case, I believe the library would be really helpful.
I'm glad you've found it.

Let me know if you notice anything ;)

**Comment by matczar** [comment]
Thanks!
